# Generated by Django 4.1.3 on 2023-03-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(' ', ' '), ('active', 'active'), ('inactive', 'inactive')], default=False, max_length=50, null=True),
        ),
    ]
