# Generated by Django 4.1.3 on 2023-03-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(' ', ' '), ('admin', 'admin'), ('staff', 'staff'), ('reseller', 'reseller'), ('rider', 'rider')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(' ', ' '), ('active', 'active'), ('inactive', 'inactive')], default=None, max_length=50, null=True),
        ),
    ]
