# Generated by Django 4.1.3 on 2023-03-09 05:57

import admin_site.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, verbose_name=' Username')),
                ('activity', models.CharField(max_length=250, verbose_name='Activity')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time')),
                ('role', models.CharField(max_length=100, null=True, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='By_Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, null=True, verbose_name='Product Code')),
                ('product_name', models.CharField(max_length=200, null=True, verbose_name='Product Name')),
                ('product_batch', models.CharField(max_length=200, null=True, verbose_name='Batch Number')),
                ('product_quantity', models.BigIntegerField(null=True, verbose_name='Quantity')),
                ('product_expired', models.DateField(null=True, verbose_name='Expiration Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderItem_transactionNo', models.CharField(max_length=200, null=True, verbose_name='Transaction Number')),
                ('OrderItem_category', models.CharField(max_length=200, verbose_name='Category')),
                ('OrderItem_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('OrderItem_unit', models.CharField(max_length=200, null=True, verbose_name='Unit')),
                ('OrderItem_quantity', models.CharField(max_length=200, null=True, verbose_name='quantity')),
                ('OrderItem_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_user', models.CharField(default=None, max_length=200, verbose_name='List user')),
                ('pos_pcode', models.CharField(max_length=200, verbose_name='Product Code')),
                ('pos_category', models.CharField(max_length=200, verbose_name='Category')),
                ('pos_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('pos_unit', models.CharField(max_length=200, verbose_name='Unit')),
                ('pos_reseller_price', models.CharField(max_length=200, null=True, verbose_name='Reseller Price')),
                ('pos_price', models.CharField(max_length=200, null=True, verbose_name='Pos Price')),
                ('pos_quantity', models.BigIntegerField(null=True, verbose_name='quantity')),
                ('pos_ResellerAmount', models.CharField(max_length=200, null=True, verbose_name='Reseller Amount')),
                ('pos_amount', models.CharField(max_length=200, null=True, verbose_name='Pos Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Pos_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_user', models.CharField(default=None, max_length=200, verbose_name='Role')),
                ('pos_no', models.CharField(max_length=200, null=True, verbose_name='Pos No')),
                ('pos_TotalAmount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Total Amount')),
                ('pos_cash', models.BigIntegerField(null=True, verbose_name='Cash')),
                ('pos_change', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Change')),
                ('pos_status', models.CharField(choices=[('Printed', 'Printed'), ('not Print', 'not Print')], max_length=250, null=True, verbose_name='Status')),
                ('pos_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, unique=True, verbose_name='Product Code')),
                ('product_category', models.CharField(max_length=200, verbose_name='Category')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('product_unit', models.CharField(max_length=200, verbose_name='Unit')),
                ('product_ResellerPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Reseller Price')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pos Price')),
                ('product_stock', models.BigIntegerField(null=True, verbose_name='Available Stock')),
                ('product_status', models.CharField(choices=[('available', 'available'), ('not available', 'not available')], max_length=200, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_user', models.CharField(max_length=100, verbose_name='List User')),
                ('profile_fname', models.CharField(max_length=250, verbose_name='First Name')),
                ('profile_mname', models.CharField(max_length=250, verbose_name='Middle Name')),
                ('profile_lname', models.CharField(max_length=250, verbose_name='Last Name')),
                ('profile_cnumber', models.BigIntegerField(verbose_name='Contact Number')),
                ('profile_address', models.TextField(verbose_name='Address')),
                ('profile_email', models.CharField(max_length=100, verbose_name='Email Address')),
                ('profile_pic', models.ImageField(null=True, upload_to=admin_site.models.image_path, verbose_name='Profile Pic')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_no', models.CharField(max_length=250, verbose_name='Promo Code')),
                ('promo_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('promo_discount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('promo_status', models.CharField(choices=[('', ''), ('active', 'active'), ('inactive', 'inactive')], max_length=250, null=True, verbose_name='Promo Status')),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('reseller_mname', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('reseller_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('reseller_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
                ('reseller_contact', models.CharField(max_length=12, verbose_name='Contact Number')),
                ('reseller_address', models.TextField(verbose_name='Address')),
                ('reseller_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('reseller_id', models.ImageField(upload_to=admin_site.models.image_path, verbose_name='valid id')),
                ('reseller_businessp', models.ImageField(upload_to=admin_site.models.image_path, verbose_name='business id')),
                ('reseller_status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], max_length=200, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=200, unique=True, verbose_name='Transaction Number')),
                ('transaction_user', models.CharField(max_length=250, null=True, verbose_name='List Username')),
                ('transaction_fname', models.CharField(max_length=250, null=True, verbose_name='First Name')),
                ('transaction_lname', models.CharField(max_length=250, null=True, verbose_name='Last Name')),
                ('transaction_address', models.TextField(verbose_name='Address')),
                ('transaction_contactno', models.BigIntegerField(null=True, verbose_name='Contact Number')),
                ('transaction_doption', models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], max_length=250, null=True, verbose_name='Delivery Option')),
                ('transaction_preferred_date', models.CharField(max_length=250, null=True, verbose_name='Preferred Date')),
                ('transaction_totalprice', models.CharField(max_length=250, null=True, verbose_name='Total Price')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date Ordered')),
                ('transaction_orderstatus', models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Status')),
                ('transaction_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Delivered Time')),
            ],
        ),
    ]
