# Generated by Django 4.1.3 on 2023-03-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ResellerPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Reseller Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Pos Price'),
        ),
    ]
