# Generated by Django 4.1.3 on 2023-03-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_alter_product_product_resellerprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='pos_ResellerAmount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Reseller Amount'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Pos Amount'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Pos Price'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_reseller_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Reseller Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Total Price'),
        ),
    ]
