# Generated by Django 4.1.3 on 2023-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_alter_pos_pos_reselleramount_alter_pos_pos_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.BigIntegerField(null=True, verbose_name='Pos Price'),
        ),
    ]
