# Generated by Django 4.1.3 on 2023-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='pos_ResellerAmount',
            field=models.BigIntegerField(null=True, verbose_name='Reseller Amount'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_amount',
            field=models.BigIntegerField(null=True, verbose_name='POS Amount'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_price',
            field=models.BigIntegerField(null=True, verbose_name='POS Price'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_reseller_price',
            field=models.BigIntegerField(null=True, verbose_name='Reseller Price'),
        ),
        migrations.AlterField(
            model_name='pos_payment',
            name='pos_TotalAmount',
            field=models.BigIntegerField(null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ResellerPrice',
            field=models.BigIntegerField(null=True, verbose_name='Reseller Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_totalprice',
            field=models.BigIntegerField(null=True, verbose_name='Total Price'),
        ),
    ]
