# Generated by Django 4.1.2 on 2023-03-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_alter_promo_promo_amount_alter_promo_promo_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Shipping', 'Out for Shipping'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Status'),
        ),
    ]
