# Generated by Django 4.1.3 on 2023-03-11 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_alter_transaction_transaction_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.CharField(default=None, max_length=200, verbose_name='List user')),
                ('cart_pcode', models.CharField(max_length=200, verbose_name='Product Code')),
                ('cart_category', models.CharField(max_length=200, verbose_name='Category')),
                ('cart_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('cart_unit', models.CharField(max_length=200, verbose_name='Unit')),
                ('cart_reseller_price', models.BigIntegerField(null=True, verbose_name='Reseller Price')),
                ('cart_price', models.BigIntegerField(null=True, verbose_name='POS Price')),
                ('cart_quantity', models.BigIntegerField(null=True, verbose_name='quantity')),
                ('cart_ResellerAmount', models.BigIntegerField(null=True, verbose_name='Reseller Amount')),
                ('cart_amount', models.BigIntegerField(null=True, verbose_name='POS Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.CharField(default=None, max_length=200, verbose_name='Role')),
                ('cart_no', models.CharField(max_length=200, null=True, verbose_name='Pos No')),
                ('cart_TotalAmount', models.BigIntegerField(null=True, verbose_name='Total Amount')),
                ('cart_cash', models.BigIntegerField(null=True, verbose_name='Cash')),
                ('cart_change', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Change')),
                ('cart_status', models.CharField(choices=[('Printed', 'Printed'), ('not Print', 'not Print')], max_length=250, null=True, verbose_name='Status')),
                ('cart_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Pos',
        ),
        migrations.DeleteModel(
            name='Pos_Payment',
        ),
    ]
