# Generated by Django 4.1.3 on 2023-04-13 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
