# Generated by Django 4.1.3 on 2023-04-13 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0012_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date Created'),
        ),
    ]
