# Generated by Django 4.1.3 on 2023-04-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0013_alter_cart_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
