# Generated by Django 4.1.3 on 2023-04-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0014_delete_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AddField(
            model_name='by_batch',
            name='product_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='OrderItem_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('available', 'available'), ('not available', 'not available'), ('low stock', 'low stock')], max_length=200, verbose_name='Status'),
        ),
    ]
