# Generated by Django 4.1.3 on 2023-04-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0015_remove_cart_created_at_by_batch_product_flavor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_category', models.CharField(max_length=250, null=True, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Settings_flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_flavor', models.CharField(max_length=250, null=True, verbose_name='Flavor')),
            ],
        ),
        migrations.CreateModel(
            name='Settings_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_unit', models.CharField(max_length=250, null=True, verbose_name='Unit')),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
