# Generated by Django 4.1.2 on 2023-04-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0016_settings_category_settings_flavor_settings_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_payment',
            name='cart_change',
            field=models.BigIntegerField(null=True, verbose_name='change'),
        ),
    ]
