# Generated by Django 4.1.2 on 2023-04-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0018_return_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='return_product',
            name='product_unit',
        ),
    ]
