# Generated by Django 4.1.2 on 2023-04-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0019_remove_return_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_product',
            name='product_status',
            field=models.CharField(choices=[('', ''), ('returned', 'returned'), ('unreturned', 'unreturned')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='return_product',
            name='return_date',
            field=models.DateField(verbose_name='Return Date'),
        ),
    ]
