# Generated by Django 4.1.2 on 2023-04-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0020_alter_return_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_product',
            name='return_date',
            field=models.CharField(max_length=200, null=True, verbose_name='Return Date'),
        ),
    ]
