# Generated by Django 4.1.2 on 2023-04-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0022_rename_product_status_return_product_return_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='by_batch',
            name='product_quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
    ]
