# Generated by Django 4.2 on 2023-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0024_review_profile_profile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_about',
            field=models.TextField(null=True),
        ),
    ]
