# Generated by Django 4.2 on 2023-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0025_alter_profile_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_about',
            field=models.TextField(max_length=250, null=True, verbose_name='About'),
        ),
    ]
