# Generated by Django 4.2 on 2023-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0026_alter_profile_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_product',
            name='return_completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Returned Completed'),
        ),
    ]
