# Generated by Django 4.2 on 2023-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0027_return_product_return_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_payment',
            name='pos_number',
            field=models.CharField(max_length=200, null=True, verbose_name='Pos Number'),
        ),
        migrations.AlterField(
            model_name='cart_payment',
            name='cart_no',
            field=models.CharField(max_length=200, null=True, verbose_name='cart No'),
        ),
    ]
