# Generated by Django 4.2 on 2023-05-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0028_cart_payment_pos_number_alter_cart_payment_cart_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Status'),
        ),
    ]
